### ISSUE TITLE
Grafana-reporter command is not working 

### ISSUE THREAD

**Issue by vanajavamsi** [IzakMarais/issueUploads#1]
Can you help on this grafana-reporter command is not working its showing command not found after installing the grafana-reporter i think the installation not done may be

**Comment by IzakMarais** [comment]
Probably post this issue in the wrong repo. Looks like it should be in reporter. 

As [mentioned in the readme](https://github.com/IzakMarais/reporter#getting-started), after installing, the reporter will be in $GOPATH/bin. You should have received some error from the go compiler if it is not there.
